site_name: Competitive Programming
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep blue
      accent: deep blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep blue
      accent: deep blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: favicon.ico
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
docs_dir: docs
repo_url: https://github.com/shivanshu-semwal/competitive-programming
edit_uri: edit/master/docs/
copyright: Copyright Shivanshu Semwal
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
plugins:
  - macros
  - search
  - git-revision-date-localized:
      enable_creation_date: true